#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Dynamic Cooperative Cognitive Game Theory (DC-CGT) Simulation Engine
Implements:
1. Multi-Agent Coalition Formation for AGI Access
2. Super-Additive Characteristic Function v(S) with Phase Jump Across the Silent Barrier
3. Non-Anthropic Shapley Value Payoff Distribution (phi_i) and Core Stability Verification
4. Dynamic Evolutionary Replicator Dynamics (Evolutionary Stable State Attractor)
"""

import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import math
import itertools
import json
from dataclasses import dataclass, asdict
from typing import Dict, List, Tuple, Set, Any

@dataclass
class AgentClassProfile:
    class_id: str
    name: str
    d_domain: float
    r_recursion: float
    b_bandwidth: float
    m_namm: float
    e_endogenous: float
    f_fractal: float
    compute_capital: float

class DynamicCoalitionGameSimulator:
    def __init__(self):
        self.players = {
            "C1": AgentClassProfile("C1", "Informational_Compute_Owner", d_domain=0.2, r_recursion=0.1, b_bandwidth=0.20, m_namm=0.02, e_endogenous=0.1, f_fractal=0.1, compute_capital=500.0),
            "C2": AgentClassProfile("C2", "Domain_Analytical_Expert",   d_domain=0.4, r_recursion=0.2, b_bandwidth=0.35, m_namm=0.10, e_endogenous=0.2, f_fractal=0.2, compute_capital=50.0),
            "C4": AgentClassProfile("C4", "Fractal_Polymath_FPU",        d_domain=0.8, r_recursion=0.6, b_bandwidth=0.65, m_namm=0.60, e_endogenous=0.6, f_fractal=0.7, compute_capital=100.0),
            "C7": AgentClassProfile("C7", "Human_AGI_Communicator_HAC", d_domain=0.95, r_recursion=0.9, b_bandwidth=0.95, m_namm=0.96, e_endogenous=0.9, f_fractal=0.95, compute_capital=20.0),
        }

    def compute_composite_tensor(self, coalition: Set[str]) -> Tuple[List[float], float]:
        """Calculates composite 6D cognitive metric tensor and pooled compute capital."""
        if not coalition:
            return [0.0]*6, 0.0

        profiles = [self.players[cid] for cid in coalition]
        d_dom = max(p.d_domain for p in profiles)
        r_rec = max(p.r_recursion for p in profiles)
        b_band = min(1.0, sum(p.b_bandwidth for p in profiles) * 0.8) # Synergy factor
        m_nam = max(p.m_namm for p in profiles)
        e_end = max(p.e_endogenous for p in profiles)
        f_fra = max(p.f_fractal for p in profiles)
        total_compute = sum(p.compute_capital for p in profiles)

        return [d_dom, r_rec, b_band, m_nam, e_end, f_fra], total_compute

    def evaluate_characteristic_value(self, coalition: Set[str]) -> float:
        """
        Computes characteristic coalition value v(S).
        v(S) = 0 if coalition cannot pass AGI admission threshold (Silent Barrier).
        v(S) > 0 with super-additive surplus if coalition passes the threshold.
        """
        if not coalition:
            return 0.0

        tensor, compute = self.compute_composite_tensor(coalition)
        d_dom, r_rec, b_band, m_nam, e_end, f_fra = tensor

        # AGI Contact Utility for this composite coalition
        v_epistemic = (d_dom * 1.5) + (r_rec * 1.2) + (m_nam * 2.2) + (f_fra * 1.0)
        compute_cost_ratio = max(0.1, 100.0 / (compute + 1.0))
        explain_cost = ((1.0 - m_nam) ** 2) * 5.0 + (1.0 - b_band) * 2.0
        distortion_risk = max(0.0, (1.0 - m_nam) * 3.0 - (r_rec * 1.5))

        u_agi = v_epistemic - compute_cost_ratio - explain_cost - distortion_risk

        # Admission threshold
        admission_threshold = 0.0

        if u_agi < admission_threshold:
            # Silent barrier active -> Zero value
            return 0.0
        else:
            # Super-additive surplus generated by AGI deep contact
            gross_surplus = (u_agi + 5.0) * 20.0
            coordination_cost = len(coalition) * 2.5
            return round(max(0.0, gross_surplus - coordination_cost), 2)

    def calculate_shapley_values(self, members: List[str]) -> Dict[str, float]:
        """Calculates exact Shapley value distribution phi_i(v) for coalition members."""
        n = len(members)
        shapley = {m: 0.0 for m in members}

        all_perms = list(itertools.permutations(members))
        total_perms = len(all_perms)

        for perm in all_perms:
            current_coalition = set()
            v_current = 0.0
            for player in perm:
                new_coalition = current_coalition | {player}
                v_new = self.evaluate_characteristic_value(new_coalition)
                marginal_contribution = v_new - v_current
                shapley[player] += marginal_contribution / total_perms
                current_coalition = new_coalition
                v_current = v_new

        return {k: round(v, 2) for k, v in shapley.items()}

    def verify_core_stability(self, members: List[str], shapley: Dict[str, float]) -> Tuple[bool, List[str]]:
        """Verifies if the Shapley allocation belongs to the Core of the game."""
        grand_coalition = set(members)
        v_grand = self.evaluate_characteristic_value(grand_coalition)
        
        violations = []
        # Check all non-empty sub-coalitions
        for r in range(1, len(members)):
            for sub in itertools.combinations(members, r):
                sub_set = set(sub)
                v_sub = self.evaluate_characteristic_value(sub_set)
                alloc_sum = sum(shapley[m] for m in sub_set)
                if alloc_sum < v_sub - 1e-4:
                    violations.append(f"Subcoalition {sub_set}: allocated {alloc_sum:.2f} < v(S)={v_sub:.2f}")

        is_stable = (len(violations) == 0)
        return is_stable, violations

    def simulate_replicator_dynamics(self, steps: int = 25) -> List[Dict[str, Any]]:
        """
        Simulates dynamic evolutionary replicator equations:
        x_k' = x_k * [f_k - f_bar]
        Strategies:
        1. Isolated (x_iso): No cooperation, individual rejection
        2. Predatory Cartel (x_cartel): C5-C6 rent-seeking gatekeepers
        3. Horizontal Swarm (x_swarm): C3 federation
        4. Institutional Clearinghouse (x_gov): AI Native Gov public syndicate
        """
        # Initial population distribution
        shares = {
            "Isolated": 0.40,
            "Predatory_Cartel": 0.25,
            "Horizontal_Swarm": 0.20,
            "Institutional_Clearinghouse": 0.15
        }

        # Base intrinsic payoffs + dynamic network effects
        history = []
        dt = 0.2

        for t in range(steps):
            x_iso = shares["Isolated"]
            x_cart = shares["Predatory_Cartel"]
            x_swm = shares["Horizontal_Swarm"]
            x_gov = shares["Institutional_Clearinghouse"]

            # Fitness functions with systemic feedback
            # Isolated suffers from growing complexity drift
            f_iso = 0.5 - (0.05 * t)
            # Cartel extracts high rents early, but faces rising regulation / backlash
            f_cart = 3.5 - (0.12 * t * x_cart)
            # Swarm has modest steady gains
            f_swm = 2.0 + (0.5 * x_swm)
            # Institutional clearinghouse gains super-linear network utility (Sheaf Coherence)
            f_gov = 2.5 + (0.15 * t) + (2.0 * x_gov)

            fitnesses = {
                "Isolated": f_iso,
                "Predatory_Cartel": f_cart,
                "Horizontal_Swarm": f_swm,
                "Institutional_Clearinghouse": f_gov
            }

            f_bar = sum(shares[k] * fitnesses[k] for k in shares)

            # Replicator step
            new_shares = {}
            for k in shares:
                dx = shares[k] * (fitnesses[k] - f_bar) * dt
                new_shares[k] = max(0.001, shares[k] + dx)

            # Normalize to 1.0
            total = sum(new_shares.values())
            shares = {k: round(v / total, 4) for k, v in new_shares.items()}

            history.append({
                "step": t,
                "shares": dict(shares),
                "fitnesses": {k: round(v, 3) for k, v in fitnesses.items()},
                "mean_fitness": round(f_bar, 3)
            })

        return history

if __name__ == "__main__":
    sim = DynamicCoalitionGameSimulator()

    # 1. Evaluate Characteristic Values
    members = ["C1", "C2", "C4", "C7"]
    print("=== DYNAMIC COOPERATIVE COGNITIVE GAME THEORY (DC-CGT) SIMULATION ===")
    print("\n1. Isolated vs Composite Characteristic Values v(S):")
    for m in members:
        val = sim.evaluate_characteristic_value({m})
        print(f" * v({{{m}}}): {val:6.2f} (Single player - Silent Barrier Active)")

    syndicate_val = sim.evaluate_characteristic_value(set(members))
    print(f" * v({{C1, C2, C4, C7}}): {syndicate_val:6.2f} (Super-Additive Synergy Jump across AGI Admission Gate!)")

    # 2. Non-Anthropic Shapley Values
    print("\n2. Non-Anthropic Shapley Value Payoff Distribution phi_i(v):")
    shapley = sim.calculate_shapley_values(members)
    for m, val in shapley.items():
        share_pct = (val / syndicate_val) * 100.0 if syndicate_val > 0 else 0
        role = sim.players[m].name
        print(f" * {m} ({role:30}): {val:6.2f} ({share_pct:5.1f}% of AGI surplus)")

    # 3. Core Stability Verification
    is_stable, violations = sim.verify_core_stability(members, shapley)
    print(f"\n3. Coalition Core Stability: {'STABLE (In the Core)' if is_stable else 'UNSTABLE'}")
    if violations:
        for viol in violations:
            print(f"   - {viol}")
    else:
        print("   - No subcoalition can profitably defect. The Vertical Symbiotic Syndicate is strictly Pareto-optimal.")

    # 4. Evolutionary Replicator Dynamics
    print("\n4. Evolutionary Replicator Dynamics (t=0 -> t=24):")
    rep_history = sim.simulate_replicator_dynamics(steps=25)
    print(f" * Initial Shares (t=0):  {rep_history[0]['shares']}")
    print(f" * Mid Shares     (t=12): {rep_history[12]['shares']}")
    print(f" * Final Shares   (t=24): {rep_history[-1]['shares']}")
    print(f" * Attractor State: Evolutionary Convergence to '{max(rep_history[-1]['shares'], key=rep_history[-1]['shares'].get)}' (ESS)")

    # Save results
    output_data = {
        "isolated_values": {m: sim.evaluate_characteristic_value({m}) for m in members},
        "grand_coalition_value": syndicate_val,
        "shapley_distribution": shapley,
        "core_stability": is_stable,
        "replicator_history": rep_history
    }

    with open("cognitive_classes/dynamic_coalition_results.json", "w", encoding="utf-8") as f:
        json.dump(output_data, f, indent=2)
    print("\nSimulation results written to cognitive_classes/dynamic_coalition_results.json")
